"""add analysis status

Revision ID: ec0bf6ebef24
Revises: 8b00c347ce76
Create Date: 2026-09-10 20:47:03.067200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0bf6ebef24'
down_revision: Union[str, Sequence[str], None] = "3563213a080e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('match_analyses', 'overall_match_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('resume_analyses', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analyses', 'status')
    op.alter_column('match_analyses', 'overall_match_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('job_analyses', 'status')
    # ### end Alembic commands ###
