"""add embedding chunk type

Revision ID: fb1208f7bb47
Revises: edde3e2a8a75
Create Date: 2026-09-16 10:59:14.365811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1208f7bb47'
down_revision: Union[str, Sequence[str], None] = 'edde3e2a8a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('chunk_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_embeddings_chunk_type'), 'embeddings', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_embeddings_source_type'), 'embeddings', ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_embeddings_source_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_chunk_type'), table_name='embeddings')
    op.drop_column('embeddings', 'chunk_type')
    # ### end Alembic commands ###
